//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.239.1.156;Initial Catalog=DBPrintLabel;Persist Security Info=True;" +
            "User ID=admin;Password=123456")]
        public string DBPrintLabelConnectionString {
            get {
                return ((string)(this["DBPrintLabelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TVC-IT-004;Initial Catalog=DBPrintLabel;Persist Security Info=True;Us" +
            "er ID=sa;Password=hung123@")]
        public string DBPrintLabelConnectionString1 {
            get {
                return ((string)(this["DBPrintLabelConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.239.1.156;Initial Catalog=DBPrintLabel;User ID=sa;Password=123456")]
        public string DBPrintLabelConnectionString2 {
            get {
                return ((string)(this["DBPrintLabelConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TVC-IT-018;Initial Catalog=DBPrintLabel_ver02;Persist Security Info=T" +
            "rue;User ID=sa;Password=hung123@")]
        public string DBPrintLabel_ver02ConnectionString {
            get {
                return ((string)(this["DBPrintLabel_ver02ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TVC-IT-018;Initial Catalog=DBPrintLabel_ver02;User ID=sa;Password=hun" +
            "g123@")]
        public string DBPrintLabel_ver02ConnectionString1 {
            get {
                return ((string)(this["DBPrintLabel_ver02ConnectionString1"]));
            }
        }
    }
}
